/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdmissionPointTeacher } from './admissionPointTeacher';
import { EnrollmentPeriod } from './enrollmentPeriod';
import { ProfileActionLog } from './profileActionLog';
import { ProfileBriefTemplate } from './profileBriefTemplate';
import { User } from './user';

export interface AdmissionProfile { 
    id?: number;
    enrollmentId?: number;
    fullName?: string;
    email?: string;
    numberphone?: string;
    status?: string;
    creatorId?: number;
    noteText?: string;
    createdAt?: Date;
    updatedAt?: Date;
    creator?: User;
    enrollment?: EnrollmentPeriod;
    admissionPointTeachers?: Array<AdmissionPointTeacher>;
    profileActionLogs?: Array<ProfileActionLog>;
    profileBriefTemplates?: Array<ProfileBriefTemplate>;
}