/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdmissionProfile } from './admissionProfile';
import { User } from './user';

export interface AdmissionPointTeacher { 
    id?: number;
    admissionProfileId?: number;
    teacherId?: number;
    point?: number;
    creatorId?: number;
    createdAt?: Date;
    updatedAt?: Date;
    admissionProfile?: AdmissionProfile;
    creator?: User;
    teacher?: User;
}