/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AuthRegisterActionForm { 
    fullName?: string;
    email?: string;
    numberPhone?: string;
    password?: string;
    subDomain?: string;
    title?: string;
    avatar?: string;
    description?: string;
    keywords?: string;
    thumbSocial?: string;
    logo?: string;
    themeNumber?: number;
    colorTheme?: string;
}