/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdmissionProfile } from './admissionProfile';
import { EnrollmentPeriod } from './enrollmentPeriod';
import { User } from './user';

export interface ProfileActionLog { 
    id?: number;
    enrollmentId?: number;
    admissionProfileId?: number;
    actionType?: string;
    actionValue?: string;
    actorId?: number;
    createdAt?: Date;
    updatedAt?: Date;
    actor?: User;
    admissionProfile?: AdmissionProfile;
    enrollment?: EnrollmentPeriod;
}