/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdmissionProfile } from './admissionProfile';
import { BriefTemplate } from './briefTemplate';
import { EnrollmentPeriod } from './enrollmentPeriod';
import { User } from './user';

export interface ProfileBriefTemplate { 
    id?: number;
    enrollmentId?: number;
    briefTemplateId?: number;
    admissionProfileId?: number;
    creatorId?: number;
    value?: string;
    createdAt?: Date;
    updatedAt?: Date;
    admissionProfile?: AdmissionProfile;
    briefTemplate?: BriefTemplate;
    creator?: User;
    enrollment?: EnrollmentPeriod;
}