/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiteCategory } from './siteCategory';
import { SiteSetting } from './siteSetting';
import { User } from './user';

export interface SitePost { 
    id?: number;
    slug?: string;
    creatorId?: number;
    name?: string;
    description?: string;
    strContent?: string;
    keywords?: string;
    thumbSocial?: string;
    tenantId?: number;
    siteId?: number;
    categoryId?: number;
    createdAt?: Date;
    updatedAt?: Date;
    category?: SiteCategory;
    creator?: User;
    site?: SiteSetting;
    tenant?: User;
}