/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiteMedia } from './siteMedia';
import { SitePost } from './sitePost';
import { SiteSetting } from './siteSetting';
import { User } from './user';

export interface SiteCategory { 
    id?: number;
    slug?: string;
    parentId?: number;
    creatorId?: number;
    name?: string;
    description?: string;
    strContent?: string;
    keywords?: string;
    thumbSocial?: string;
    tenantId?: number;
    siteId?: number;
    useBanner?: number;
    layoutOnlyAlbum?: number;
    createdAt?: Date;
    updatedAt?: Date;
    creator?: User;
    parent?: SiteCategory;
    site?: SiteSetting;
    tenant?: User;
    inverseParent?: Array<SiteCategory>;
    siteMedia?: Array<SiteMedia>;
    sitePosts?: Array<SitePost>;
}