/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BooleanCommonResponse } from '../model/booleanCommonResponse';
import { EnrollmentTeacherRequest } from '../model/enrollmentTeacherRequest';
import { UpsertPointProfileRequest } from '../model/upsertPointProfileRequest';
import { UserListCommonResponse } from '../model/userListCommonResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EnrollmentTeacherService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param enrollmentId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentTeacherEnrollmentIdGet(enrollmentId: number, observe?: 'body', reportProgress?: boolean): Observable<UserListCommonResponse>;
    public apiEnrollmentTeacherEnrollmentIdGet(enrollmentId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserListCommonResponse>>;
    public apiEnrollmentTeacherEnrollmentIdGet(enrollmentId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserListCommonResponse>>;
    public apiEnrollmentTeacherEnrollmentIdGet(enrollmentId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (enrollmentId === null || enrollmentId === undefined) {
            throw new Error('Required parameter enrollmentId was null or undefined when calling apiEnrollmentTeacherEnrollmentIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UserListCommonResponse>('get',`${this.basePath}/api/enrollment-teacher/${encodeURIComponent(String(enrollmentId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param enrollmentId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentTeacherEnrollmentIdPointPost(enrollmentId: number, body?: UpsertPointProfileRequest, observe?: 'body', reportProgress?: boolean): Observable<BooleanCommonResponse>;
    public apiEnrollmentTeacherEnrollmentIdPointPost(enrollmentId: number, body?: UpsertPointProfileRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BooleanCommonResponse>>;
    public apiEnrollmentTeacherEnrollmentIdPointPost(enrollmentId: number, body?: UpsertPointProfileRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BooleanCommonResponse>>;
    public apiEnrollmentTeacherEnrollmentIdPointPost(enrollmentId: number, body?: UpsertPointProfileRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (enrollmentId === null || enrollmentId === undefined) {
            throw new Error('Required parameter enrollmentId was null or undefined when calling apiEnrollmentTeacherEnrollmentIdPointPost.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<BooleanCommonResponse>('post',`${this.basePath}/api/enrollment-teacher/${encodeURIComponent(String(enrollmentId))}/point`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param enrollmentId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentTeacherEnrollmentIdPost(enrollmentId: number, body?: EnrollmentTeacherRequest, observe?: 'body', reportProgress?: boolean): Observable<BooleanCommonResponse>;
    public apiEnrollmentTeacherEnrollmentIdPost(enrollmentId: number, body?: EnrollmentTeacherRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BooleanCommonResponse>>;
    public apiEnrollmentTeacherEnrollmentIdPost(enrollmentId: number, body?: EnrollmentTeacherRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BooleanCommonResponse>>;
    public apiEnrollmentTeacherEnrollmentIdPost(enrollmentId: number, body?: EnrollmentTeacherRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (enrollmentId === null || enrollmentId === undefined) {
            throw new Error('Required parameter enrollmentId was null or undefined when calling apiEnrollmentTeacherEnrollmentIdPost.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<BooleanCommonResponse>('post',`${this.basePath}/api/enrollment-teacher/${encodeURIComponent(String(enrollmentId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
