/**
 * Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BooleanCommonResponse } from '../model/booleanCommonResponse';
import { EnrollmentPeriodCommonResponse } from '../model/enrollmentPeriodCommonResponse';
import { EnrollmentPeriodListCommonResponse } from '../model/enrollmentPeriodListCommonResponse';
import { EnrollmentPeriodRequest } from '../model/enrollmentPeriodRequest';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EnrollmentPeriodService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentPeriodGet(observe?: 'body', reportProgress?: boolean): Observable<EnrollmentPeriodListCommonResponse>;
    public apiEnrollmentPeriodGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EnrollmentPeriodListCommonResponse>>;
    public apiEnrollmentPeriodGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EnrollmentPeriodListCommonResponse>>;
    public apiEnrollmentPeriodGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<EnrollmentPeriodListCommonResponse>('get',`${this.basePath}/api/enrollment-period`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentPeriodIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<BooleanCommonResponse>;
    public apiEnrollmentPeriodIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BooleanCommonResponse>>;
    public apiEnrollmentPeriodIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BooleanCommonResponse>>;
    public apiEnrollmentPeriodIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiEnrollmentPeriodIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BooleanCommonResponse>('delete',`${this.basePath}/api/enrollment-period/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentPeriodIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<EnrollmentPeriodCommonResponse>;
    public apiEnrollmentPeriodIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EnrollmentPeriodCommonResponse>>;
    public apiEnrollmentPeriodIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EnrollmentPeriodCommonResponse>>;
    public apiEnrollmentPeriodIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiEnrollmentPeriodIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<EnrollmentPeriodCommonResponse>('get',`${this.basePath}/api/enrollment-period/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentPeriodIdPatch(id: number, body?: EnrollmentPeriodRequest, observe?: 'body', reportProgress?: boolean): Observable<EnrollmentPeriodCommonResponse>;
    public apiEnrollmentPeriodIdPatch(id: number, body?: EnrollmentPeriodRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EnrollmentPeriodCommonResponse>>;
    public apiEnrollmentPeriodIdPatch(id: number, body?: EnrollmentPeriodRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EnrollmentPeriodCommonResponse>>;
    public apiEnrollmentPeriodIdPatch(id: number, body?: EnrollmentPeriodRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiEnrollmentPeriodIdPatch.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<EnrollmentPeriodCommonResponse>('patch',`${this.basePath}/api/enrollment-period/${encodeURIComponent(String(id))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentPeriodPost(body?: EnrollmentPeriodRequest, observe?: 'body', reportProgress?: boolean): Observable<EnrollmentPeriodCommonResponse>;
    public apiEnrollmentPeriodPost(body?: EnrollmentPeriodRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EnrollmentPeriodCommonResponse>>;
    public apiEnrollmentPeriodPost(body?: EnrollmentPeriodRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EnrollmentPeriodCommonResponse>>;
    public apiEnrollmentPeriodPost(body?: EnrollmentPeriodRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<EnrollmentPeriodCommonResponse>('post',`${this.basePath}/api/enrollment-period`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
